[main]
plugins=keyfile

[keyfile]

# Alpine builds NetworkManager with ifupdown as the compiled-in default plugin, which treats any
# interface absent from /etc/network/interfaces (which Kira doesn't use) as unmanaged
[ifupdown]
managed=true
